logger:
  name: smart-home
  level: 0
  console:
    enable: true
    level: 0
  file:
    enable: true
    level: 0
    path: auto

audio:
  reader:
    out_topic: "/audio/reader/stream"
    out_sample_rate: 16000

kws:
  in_sample_rate: 16000
  in_topic: "/audio/reader/stream"
  out_topic: "/kws/wakeup"
  model:
    transducer:
      encoder: "encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx"
      decoder: "decoder-epoch-12-avg-2-chunk-16-left-64.onnx"
      joiner: "joiner-epoch-12-avg-2-chunk-16-left-64.int8.onnx"
    tokens: "tokens.txt"
    debug: false
  keywords:
    path: "keywords.txt"

recognizer:
  in_topic: "/kws/wakeup"
  in_sample_rate: 16000
  in_max_size: 10
  out_topic: "/recognizer/stream"
  model:
    encoder: "encoder-epoch-12-avg-2-chunk-16-left-64.int8.onnx"
    decoder: "decoder-epoch-12-avg-2-chunk-16-left-64.onnx"
    tokens: "tokens.txt"

nlu:
  
